name: Publish Docker Image

on:
  push:
    branches:
      - "**"
    tags:
      - v*
  pull_request:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      - name: Generate image tags
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: |
            ghcr.io/spaceface16518/raspberrypi-monitor
          tag-match: 'v\d{1,3}\.\d{1,3}\.\d{1,3}'
          tag-match-latest: true
          tag-edge: true
          tag-sha: true
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v5, linux/arm/v6,linux/arm/v7,linux/arm64/v8, linux/mips64le, linux/ppc64le, linux/s390x
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
